#!/usr/bin/python3
"""function that raises a name exception with a message
Return: the exception raised.
"""


def raise_exception_msg(message=""):
    raise NameError(message)
